version: 1.1.11-adhoc.123
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.123
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.123
deployedAt: 2019-02-26 1:10 am UTC  (2019-02-25 5:10 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-25--5.08pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-25--5.08pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/be0bb23c33b6bc3f9a642b4654ca758b344dc4bc
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-25--5.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a7c2986c494ca133d1d4a318ecf8d8817b141f9a
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-25--5.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/63bfdd5247d2933f3387d7b984446da594037ace
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e7e56798e64dcdfcbfe6d59a15c9d49fb2c0a61a
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a784955b076fbf61c7c5479c266821f20ba99e6e
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-25--5.08pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.123/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.123/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/498487460