tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-01-17--2.35pm
    commitMessage: __adhoc--beta--local-enlistment--2019-01-17--2.35pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/788cffcc2e2a619685ae18afac1cf2c22d157888
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-01-17--2.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7fa39ec33b55716cd6dd760dd8abffc930e67abc
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-01-17--2.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/58c645d602cd0d08363f03b1555d21ff9d44b470
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8c131db1c77e2af09dafe533546d4169958e84c6
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/357bbcf7e31fa3232a92db338913fb152ff80834
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-01-17--2.35pm
