version: 1.1.11-adhoc.93
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.93
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.93
deployedAt: 2019-02-12 3:03 am UTC  (2019-02-11 7:03 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-11--7.01pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-11--7.01pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dbb51eb1dd072f8d75ae233e10ed3f585562c3f4
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-11--7.01pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/90d8848a956d96f2679c01c13f1bb04a0e92b235
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-11--7.01pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/88e92eb3d79b94ae08fd71d6d58357af36d38340
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/55fb22d6db2ae38f49508bc615f6778143ff3dfa
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fd4a05e28ace2302a028536d72bbc18edf38115b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-11--7.01pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.93/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.93/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/491957288