version: 1.1.11-operational-error.0
tag: operational-error
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-operational-error.0
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-operational-error.0
deployedAt: 2019-02-04 8:13 pm UTC  (2019-02-04 12:13 pm Pacific Time)

history:
    adhocBranchName: __adhoc--operational-error--current--local--2019-02-04--12.08pm
    commitMessage: __adhoc--operational-error--current--local--2019-02-04--12.08pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d6518202a93ab4758758f64f3af0c55fcb2aaff6
            message: >-
                JS dist files --
                __adhoc--operational-error--current--local--2019-02-04--12.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4bef2eedb090728dbe0f482ed7328462b2d5e420
            message: >-
                Localized strings --
                __adhoc--operational-error--current--local--2019-02-04--12.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5ccbb41b2b6722fe128c1a3f5710e38764f29c22
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4ed4ce5a58e1e7d2df782dc19270021cd6d4c362
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/64f683a50b5d762167c348b98767f42f428470d8
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational-error--current--local--2019-02-04--12.08pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-operational-error.0/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-operational-error.0/dist/office.d.ts
    builds using this same tag ("operational-error"):
        https://unpkg.com/@microsoft/office-js@operational-error/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational-error/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/488679573