version: 1.1.11-adhoc.62
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.62
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.62
deployedAt: 2019-01-17 1:41 am UTC  (2019-01-16 5:41 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-01-16--5.37pm
    commitMessage: __adhoc--beta--local-enlistment--2019-01-16--5.37pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/10e9bc18cf8475df0be832151ed8752a6ee4504c
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-01-16--5.37pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/745b70bfcac079cc7411bccf189d1ece01bd5002
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-01-16--5.37pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a6e2d026280f34338615c0eb9e6120097fc11882
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/492e2397769dfd7e523c61c6f41f231453e48d01
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1994245b288adc617e3a469dc0977a638c1ef8fa
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-01-16--5.37pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.62/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.62/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/480670344