tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-09-13--1.19pm--online-dialog-2
    commitMessage: __adhoc--beta--local-enlistment--2018-09-13--1.19pm--online-dialog-2
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3b1072a011d3f08babb84adc1ec7718d72996267
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-09-13--1.19pm--online-dialog-2
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/65acae86fa60bf913d8395dfd802f28ee3af85f6
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-09-13--1.19pm--online-dialog-2
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2858b7cde3123f8310b2c0b19288f4ed50c5fd1f
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2fd653b55a6895f5198075263f5dcb6c393a7ca7
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fda72910254ef44abc0d9fd0997e1257c7fb519b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-09-13--1.19pm--online-dialog-2
