version: 1.1.11-adhoc.104
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.104
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.104
deployedAt: 2019-02-15 6:53 am UTC  (2019-02-14 10:53 pm Pacific Time)

history:
    adhocBranchName: __adhoc--current--local--2019-02-15--1.08pm
    commitMessage: __adhoc--current--local--2019-02-15--1.08pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/539e19d3403f092e95d4fc0a856e7bed19b3ea75
            message: JS dist files -- __adhoc--current--local--2019-02-15--1.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3e478f8ebb4d40cb9bd4cbdb12a0ea2bab4703d1
            message: Localized strings -- __adhoc--current--local--2019-02-15--1.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0698d240f902c76994d9b92fd4c0af51420e7c3e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a199d1892d8a0558f0d42c4f92fce86a57fc1710
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c2028510890095ae907903dee9db7bbcc03a6755
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--current--local--2019-02-15--1.08pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.104/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.104/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/493618605