tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-01-31--2.27pm
    commitMessage: __adhoc--beta--local-enlistment--2019-01-31--2.27pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/499e819f20f301479e90c85c7f2fc1a55b35c3f4
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-01-31--2.27pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f73db269ba1ca4c5bbbb6008979b5b4b9a348264
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-01-31--2.27pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d394cafcb3f5a49c08260669635ca49d8fda1c99
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a22f0bbf672f054ef7fb92ddee5b75e30db002fd
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5c5f4b671cc4d3c12acd0746ade78c6fc3b9f284
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-01-31--2.27pm
