tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-27--3.45pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-27--3.45pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6a69d8b1b5db0ce6794fdbce935c023b9a599e18
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-27--3.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/60a47b882559b7b4d0ea5744bacd73bd1d6db229
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-27--3.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a0e7fc3369481f5059d175467320ba03643203c1
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/79715e3752f0733d5e66446016b7a0e51d26a951
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ac3c5e8d7943a9f12709bcb3746e849274aad792
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-27--3.45pm
