tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-01--6.50pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-01--6.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/aa07ee03c8e0f896fba402fdd3983e6824b4fc59
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-01--6.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/67a610344883b2af2759055776aa5292044c34db
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-01--6.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/cd516f79269c8c55316e0d1fc385a38ecfa34c14
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8071fb08d39b72e786ae2737520315cca5d55ccb
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1c00df0f0ff30cc9f77efa316bb0361fc6646762
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-01--6.50pm
