tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-01-14--8.37am
    commitMessage: __adhoc--beta--local-enlistment--2019-01-14--8.37am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/86293045989d17582282d783eff7632207e6a314
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-01-14--8.37am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f3988e3a0db5e930c3cdf9dfec0e087cdfbeeb74
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-01-14--8.37am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b1b4088f4df6f42d06990fb66fefc61af5599685
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2a0173be610326fc7e793597f82b4dcb0d3e7df1
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ed2d63d2257a03f338f21ce1f7c5c1f8978bbcff
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-01-14--8.37am
