tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-11-12--2.39pm
    commitMessage: __adhoc--beta--local--2018-11-12--2.39pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0461a2cf3072edd7bb6e67d2d2cf3ee3eb540832
            message: JS dist files -- __adhoc--beta--local--2018-11-12--2.39pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/04a3f80f26409c7bed7221f27905a38a4b0ff905
            message: Localized strings -- __adhoc--beta--local--2018-11-12--2.39pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6f5603a67e25cf10720ff0e70917522f51f5bd23
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/cfc0cfd49062bf4852f5eec4f88fc59103394b31
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4a33381a0efa1c3701b023b883b048425a7bb19b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-11-12--2.39pm
