tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-11-13--4.18pm
    commitMessage: __adhoc--beta--local--2018-11-13--4.18pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/07d883bce5c89000ae99b924e99168a43eb63b5c
            message: JS dist files -- __adhoc--beta--local--2018-11-13--4.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/daf30ce81db2ca44d62443ce5ac48fdd4406881b
            message: Localized strings -- __adhoc--beta--local--2018-11-13--4.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d0c86f1a4744bcdefec0c08f4f5325a5aee33fb3
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/33b4fa0f40e4173d646e2e6aadaa9350374e72ed
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/07e33e6e79456a86bfe025c859533ab004f7f1c2
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-11-13--4.18pm
