tag: operational
history:
    adhocBranchName: __adhoc--operational--current--local--2018-09-05--3.50pm
    commitMessage: __adhoc--operational--current--local--2018-09-05--3.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9eaf0aa90e00213f622a67b634e27ed2dde5552c
            message: >-
                JS dist files --
                __adhoc--operational--current--local--2018-09-05--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c897ff2e2929b848a802a334577c1f7c54bd659a
            message: >-
                Localized strings --
                __adhoc--operational--current--local--2018-09-05--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c180570dfc8411c8aa385c2760e1700e3c25591e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/57ea2cd776bfdfad8532bd98a16c337e38015db5
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bc5fc7ee86e08ee112bf7c529fdcb4a1b86a6f9c
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational--current--local--2018-09-05--3.50pm
