version: 1.1.11-adhoc.83
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.83
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.83
deployedAt: 2019-02-07 5:18 am UTC  (2019-02-06 9:18 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-06--9.10pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-06--9.10pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/164844209d48b70f696b470cc3d6f58cd638bf7b
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-06--9.10pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/96dba9a076c8cac92997b38a3153a586ba3ff500
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-06--9.10pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b68877017e8e6b090ab8cf11d525573a1c3bab71
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/74425d3aad4119156f3375ed958b3a0c93535153
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fcda21a4e8a9ee1fd708a507017af7a80b4e93ce
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-06--9.10pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.83/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.83/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/489890203