version: 1.1.11-operational.11
tag: operational
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-operational.11
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-operational.11
deployedAt: 2019-03-27 5:52 am UTC  (2019-03-26 10:52 pm Pacific Time)

history:
    adhocBranchName: __adhoc--operational--current--local--2019-03-26--10.48pm
    commitMessage: __adhoc--operational--current--local--2019-03-26--10.48pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/29c3f7c39be8f52b28610d583ed00e16bec26835
            message: >-
                JS dist files --
                __adhoc--operational--current--local--2019-03-26--10.48pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/03ded6c6a142219b18977790c28ef791bdf5b19e
            message: >-
                Localized strings --
                __adhoc--operational--current--local--2019-03-26--10.48pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/be7b08e2975579355dbabc0b777c41634e5821db
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/065f5fdea6ecfd21f49e023bd4e76a8bd9328e78
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/78e54c0cda513c2882619a89c492e75ff370ee4a
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational--current--local--2019-03-26--10.48pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.11/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.11/dist/office.d.ts
    builds using this same tag ("operational"):
        https://unpkg.com/@microsoft/office-js@operational/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/511850159