tag: adhoc
history:
    adhocBranchName: __adhoc--current--local--2018-09-19--2.52pm
    commitMessage: __adhoc--current--local--2018-09-19--2.52pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3b4799e85d756a963b6ed55ed64b6090b8d6facd
            message: JS dist files -- __adhoc--current--local--2018-09-19--2.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8762718bf369d1dc091721992e95720e342dbe66
            message: Localized strings -- __adhoc--current--local--2018-09-19--2.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6f2db4fcee1423f32362db45e827cf1e9d81a59e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2a7334cd08fd0478f1703af44e75f5bafab9237e
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c5d90cd3164d9f925f78b212d94251155257a62b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--current--local--2018-09-19--2.52pm
