tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-21--7.27pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-21--7.27pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/705b60bf9f7750af0f4316a72bbd19fe87ebc366
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-21--7.27pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b21bb83f5f40a781295a76b61466b387c077ba4e
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-21--7.27pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/02a6b6b4f21e57e1624f2f79c560a0445a3ed6ae
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5b91e342d6caadde6419a26ad740cb35d93769fb
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/751c79e38eed2d35ee3349d8aa0a41051ad38d06
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-21--7.27pm
