version: 1.1.11-adhoc.36
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.36
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.36
deployedAt: 2018-12-05 10:24 pm UTC  (2018-12-05 2:24 pm Pacific Time)

history:
    adhocBranchName: __adhoc--release--16.0.11204.35450--2018-12-05--2.19pm
    commitMessage: __adhoc--release--16.0.11204.35450--2018-12-05--2.19pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0329f5ccb93ec580b3950ad86d9c16d5cc687e72
            message: >-
                JS dist files --
                __adhoc--release--16.0.11204.35450--2018-12-05--2.19pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/09bbeadb19e5df0e5462c8d9f193c01d433611d3
            message: >-
                Localized strings --
                __adhoc--release--16.0.11204.35450--2018-12-05--2.19pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/af605d43c70778587d5101d6dabea046550238b8
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/189fd05243431b5f0098eace2b2ba2aef14d0daa
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f50d118ea269ad9b063cc3eef99e7eca22c11033
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--16.0.11204.35450--2018-12-05--2.19pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.36/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.36/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/464078693