version: 1.1.11-adhoc.8
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.8
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.8
deployedAt: 2018-11-05 5:51 pm UTC  (2018-11-05 9:51 am Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-11-05--9.48am
    commitMessage: __adhoc--beta--local-enlistment--2018-11-05--9.48am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dc7b5335adaecaf1ebfcfb0a7229d89c770ab059
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-11-05--9.48am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d653aa757adec2aca249f3dd769a6adef429de59
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-11-05--9.48am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/903ed77d3358df1c3bd755f78d7ecf990b9806b4
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8b88b6ad86544d5d88b859b7903dfa34a438e4bc
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/29f3bc5a271fdfedf34e36ef1ecc43d8c0d6dfdb
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-11-05--9.48am


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.8/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.8/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/450986464