version: 1.1.11-adhoc.86
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.86
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.86
deployedAt: 2019-02-08 6:06 pm UTC  (2019-02-08 10:06 am Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-08--10.03am
    commitMessage: __adhoc--beta--local-enlistment--2019-02-08--10.03am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/521704ed8336ff9c1259b5548bcc109b6cf42465
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-08--10.03am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/532bcea51bd3ec81aba8785c69c7f62a854e83f1
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-08--10.03am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/87fb2a818243376a752bf7ea1cca798f1607b12e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dc7a921127dd9bd51ad56a49e539c91c5e2647ba
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f6e13ff20fe32d712a30296dcd5f168314a9c5b5
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-08--10.03am


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.86/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.86/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/490666973