tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-22--1.50pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-22--1.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/675b444dec1d2c2448e5a11a3212c17df2ef9fb0
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-22--1.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b9e83fd6443a0875108b50414681381001730e61
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-22--1.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/84b4abf8e56c514feb0c5957eae837c5fd4ff728
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6e93bf5cdfe9579238c577284f419f1f1bbd5fee
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/786c01331135484a212adaa1edf32eade45a4437
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-22--1.50pm
