version: 1.1.11-adhoc.135
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.135
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.135
deployedAt: 2019-03-07 5:44 am UTC  (2019-03-06 9:44 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-06--9.41pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-06--9.41pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/104446809014c81867f472b657b44f79358f9c6d
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-06--9.41pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b4fd849c062784257c47d897e3abc490e51ac6ad
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-06--9.41pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5a44626749a65a4fe495e1aaa31b4017dce542e1
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7a8401146820ddfe9c2f39b97fb713c1ca476348
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e4c7fd9590db77e03da292646bc6c08ba48615bf
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-06--9.41pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.135/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.135/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/502931240