tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-04--3.52pm
    commitMessage: __adhoc--beta--local-enlistment--2018-12-04--3.52pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3eb0cb666b10ab81f398de3031e88bb6343ed397
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-04--3.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/eeee1dcedb264f8b898a544a78f2300c2f6c0220
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-04--3.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e3da68e5c7499a96e8caa0659562cf841497cf23
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/710343360977f8dc2ac3717995c5e1672aa8b0db
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8d6e6301e12aeea3be68f344f1c1369f4e7d4899
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-04--3.52pm
