tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-01-24--12.49pm
    commitMessage: __adhoc--beta--local-enlistment--2019-01-24--12.49pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b733e2dcce56c31c5777c45e45fcaf0e2d389f16
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-01-24--12.49pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8f214f277ae8822be2394c8e95f9dee963238f22
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-01-24--12.49pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5eb5fad345b1c666aea5df8d6b4f2ad56e436f3a
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/36a28be9da77a8bb44d2db60ba05d093d7561c67
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7458efa4f034a098e7b1c7eccfa8b042bed64b10
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-01-24--12.49pm
