version: 1.1.9-custom-functions-preview-refresh.2
tag: custom-functions-preview-refresh
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-custom-functions-preview-refresh.2
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-custom-functions-preview-refresh.2
deployedAt: 2018-08-10 2:53 am UTC  (2018-08-09 7:53 pm Pacific Time)

history:
    adhocBranchName: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-09--7.49pm
    commitMessage: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-09--7.49pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/39f6807700430e8127a002d429233f751a5d74e0
            message: >-
                JS dist files --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-09--7.49pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f615af9d66e66740557564e4a3f3bb76a99e1589
            message: >-
                Localized strings --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-09--7.49pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e51957fe78c5e6d82964e97d9acb248f628d6df8
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a4423e726c34cd2719ef3074be1a7deb093e10a4
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/71114c60d010cde6d6dd74ac5e1c77c75ecca8fc
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-09--7.49pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-custom-functions-preview-refresh.2/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-custom-functions-preview-refresh.2/dist/office.d.ts
    builds using this same tag ("custom-functions-preview-refresh"):
        https://unpkg.com/@microsoft/office-js@custom-functions-preview-refresh/dist/office.js
        https://unpkg.com/@microsoft/office-js@custom-functions-preview-refresh/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/414344748