version: 1.1.11-operational.16
tag: operational
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-operational.16
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-operational.16
deployedAt: 2019-04-18 11:41 pm UTC  (2019-04-18 4:41 pm Pacific Time)

history:
    adhocBranchName: __adhoc--operational--current--local--2019-04-18--4.37pm
    commitMessage: __adhoc--operational--current--local--2019-04-18--4.37pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7490255d3c615b448f78f0cbf0b06d1ddf8595ae
            message: >-
                JS dist files --
                __adhoc--operational--current--local--2019-04-18--4.37pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5e836dcc338c1326be93546014a5cd3f62987045
            message: >-
                Localized strings --
                __adhoc--operational--current--local--2019-04-18--4.37pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/244cd82b541358699cff85bf4120b2e56db123dc
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d3b0485fb9034d1126e003c9c3be03ab49bcc02a
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/42097a0e6e672055cbfc21600fe42bc9cf0dbcc5
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational--current--local--2019-04-18--4.37pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.16/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.16/dist/office.d.ts
    builds using this same tag ("operational"):
        https://unpkg.com/@microsoft/office-js@operational/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/521962063