version: 1.1.11-operational.0
tag: operational
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-operational.0
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-operational.0
deployedAt: 2018-11-05 9:00 pm UTC  (2018-11-05 1:00 pm Pacific Time)

history:
    adhocBranchName: __adhoc--operational--current--local--2018-11-05--12.56pm
    commitMessage: __adhoc--operational--current--local--2018-11-05--12.56pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/732f386983f8cf96fcd44f24dc39e27e99f93185
            message: >-
                JS dist files --
                __adhoc--operational--current--local--2018-11-05--12.56pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b1a532b4d1328ce2efa246a23bea1883405b3f0e
            message: >-
                Localized strings --
                __adhoc--operational--current--local--2018-11-05--12.56pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ccca5ea78c6cd286fc0ae1d2d8b800f5f3699f6a
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b3dcfd08d26a911ea03444431860fba1ce6e8fde
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/05c4d15e10ae84685a12c6cfbacd1dee179e0c58
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational--current--local--2018-11-05--12.56pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.0/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-operational.0/dist/office.d.ts
    builds using this same tag ("operational"):
        https://unpkg.com/@microsoft/office-js@operational/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/451070268