version: 1.1.9-custom-functions-preview-refresh.6
tag: custom-functions-preview-refresh
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-custom-functions-preview-refresh.6
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-custom-functions-preview-refresh.6
deployedAt: 2018-09-15 1:15 am UTC  (2018-09-14 6:15 pm Pacific Time)

history:
    adhocBranchName: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-14--6.12pm
    commitMessage: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-14--6.12pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/cb001c6f6e606ee80a8ca2d397a09143d3862e22
            message: >-
                JS dist files --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-14--6.12pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/35dc356b89d39dbe68d00ffa76ba62a933028dc2
            message: >-
                Localized strings --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-14--6.12pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c1aead0c20fa4bcb376e75e011a35817f6c73c79
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0e7435c459bda9ef746e5395cff4837cc9fc0924
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e57ee922701e5c5434de4591c0d04de292ed68a9
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-14--6.12pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-custom-functions-preview-refresh.6/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-custom-functions-preview-refresh.6/dist/office.d.ts
    builds using this same tag ("custom-functions-preview-refresh"):
        https://unpkg.com/@microsoft/office-js@custom-functions-preview-refresh/dist/office.js
        https://unpkg.com/@microsoft/office-js@custom-functions-preview-refresh/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/428863987