tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-06--3.29pm
    commitMessage: __adhoc--beta--local-enlistment--2018-12-06--3.29pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4a5522fb972cfdf91c92bafaa0cbb4a5d07156ab
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-06--3.29pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7c7d07cd28e77199f7de7528cfd9369e52046b96
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-06--3.29pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9a9ea97dd7c429c7aca2be9f5638e32cc3a5f194
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8de7a820caae0da98e4c2c6eae354380558540b7
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2aa5f2103a7e2e2e95ea001637d51e6ea55d804c
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-06--3.29pm
