version: 1.1.11-adhoc.137
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.137
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.137
deployedAt: 2019-03-11 5:53 am UTC  (2019-03-10 10:53 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-10--10.50pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-10--10.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/57e78eee6ff048158aa163763cb1e233c3092e64
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-10--10.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c9d1f92af5dea66f66e681d94997cc605a3495ef
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-10--10.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6b7cfdb835e6954105f06a50dd9a46351d33a339
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a1aa47507bf79d5de703232aa31bf1beb7239696
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c51bf605d8289a10b81793981df3df1901e6269b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-10--10.50pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.137/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.137/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/504533872