tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-07--11.50pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-07--11.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/000ef97096a7b8ef8d79316889b5fd051859018e
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-07--11.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/089fb5c380d57e30b558dd265396b57505197c31
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-07--11.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9553238c05087203db7d632ec2197f600e58fcf6
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3dab4d45fd84d37972231c10fe983dc922428e3e
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2e3c140763d9c9d23f10d7471c796af4a8eb525c
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-07--11.50pm
