version: 1.1.11-adhoc.21
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.21
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.21
deployedAt: 2018-11-15 9:24 pm UTC  (2018-11-15 1:24 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local--2018-11-15--1.21pm
    commitMessage: __adhoc--beta--local--2018-11-15--1.21pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/36dd8624ffbc35ad3ed6b5b2abda8c025aec77b9
            message: JS dist files -- __adhoc--beta--local--2018-11-15--1.21pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ef705e9084441913175e2446ab0440511555f4b2
            message: Localized strings -- __adhoc--beta--local--2018-11-15--1.21pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/13e7c328afaae326ef064c43f7c67ff7335776dc
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b4c8d02f27004d1d9810754446f9b46b2c607896
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/839ac2183942340714e7d0b2d72f60306d6a2b80
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-11-15--1.21pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.21/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.21/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/455703108