version: 1.1.11-adhoc.38
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.38
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.38
deployedAt: 2018-12-06 12:25 am UTC  (2018-12-05 4:25 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-05--4.22pm
    commitMessage: __adhoc--beta--local-enlistment--2018-12-05--4.22pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/70273369f175a835610c109a62bd6fb253b9fad7
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-05--4.22pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fff8109c1eeaeb5e97748383725b1d5ee3a00c97
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-05--4.22pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4eba53bfb60794a5a447ba44cd217bd9a4af73ee
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/62407d4c720764ac88fb7270fcbcc18b95e852bc
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6d545caf924e98e9623d307cec3d7a4e133e1a1f
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-05--4.22pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.38/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.38/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/464118713