version: 1.1.11-adhoc.50
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.50
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.50
deployedAt: 2018-12-14 7:30 pm UTC  (2018-12-14 11:30 am Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-14--11.27am
    commitMessage: __adhoc--beta--local-enlistment--2018-12-14--11.27am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e931015ed32dced71aae90ce095a62d195450ebb
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-14--11.27am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3a716fcade61239b544966e74412cd11e43e195a
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-14--11.27am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a0a2da82e250eb1741815b415a3ebf37ac8cb260
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/82619249c005425635910e3532fa3b8c042a85f5
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0738e908cf43aaa17bbfcb7051fd5bd294642bfe
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-14--11.27am


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.50/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.50/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/468144216