version: 1.1.9-adhoc.30
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-adhoc.30
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-adhoc.30
deployedAt: 2018-09-13 5:29 pm UTC  (2018-09-13 10:29 am Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-09-13--10.25am
    commitMessage: __adhoc--beta--local-enlistment--2018-09-13--10.25am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d549e082420d798697a8653ae3a4de218bd941c0
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-09-13--10.25am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a25e136b0d2bf559510d4fd89a5b70c0f6fe2a24
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-09-13--10.25am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4c6feb825277fbdbaddf5269cb658c368233595e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9ee1bb09769e2d976d9f61c33b62403c00ef5e3d
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8d5b57adfaa861498926f152869055f690e2882c
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-09-13--10.25am


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.30/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.30/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/428267864