version: 1.1.11-adhoc.112
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.112
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.112
deployedAt: 2019-02-22 3:28 am UTC  (2019-02-21 7:28 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-21--7.25pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-21--7.25pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/015f040595ce7ed66e5a111097b16c706e3e7585
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-21--7.25pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4e05be061912b06a24509646dbbc43fdf57fe138
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-21--7.25pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f10c608788262aeb53cd50262c50c39492105ce5
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ce43635a3a07ebc79aed753ae3eac74a86a63fb5
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4e002ebc9f54443c86c075e0a01f66abb5e7f4fb
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-21--7.25pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.112/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.112/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/496847947