tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-06--7.44pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-06--7.44pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ef85993ed8cc53b26bf1f919578517851e988880
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-06--7.44pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a3647abdfd5e8837e8eaf868a4cd50f25beccf11
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-06--7.44pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d9050c9edec1f4b6db35ef478641d289a4d95264
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/71efdc56d944bea323bcc5df93ab55e4b1877bed
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7c13dc65780b4e5e2ea5713c932edc52ba4b3170
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-06--7.44pm
