tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-05--3.42pm
    commitMessage: __adhoc--beta--local-enlistment--2018-12-05--3.42pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/befa107d87c92cf1b392d91ba2d7122ca7a1a9f5
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-05--3.42pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0b2a6c6501c8f4efcef90041ea6b2bb0ca0097f1
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-05--3.42pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f279e111a46e4d8838347c9141e2201ae713cbc5
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5ec3e199c829579dd49fb1fa60cf71c4a2c1e707
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a69a0ccf179effaa48808993bb29158540206f42
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-05--3.42pm
