tag: custom-functions-preview-refresh
history:
    adhocBranchName: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-20--3.38pm
    commitMessage: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-20--3.38pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b1264a0248f4de2d241407d1116570460f4350cf
            message: >-
                JS dist files --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-20--3.38pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2cecae2c57f5093d350604c14a522c172161cb2d
            message: >-
                Localized strings --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-20--3.38pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/303cd2346aa7ddd4c22993f7caab32fb37857971
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/74344e237d63b77e5ee8807efab353ed161700ac
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a110f3ed9f1437484fde64a79a796bc4e10efadf
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-09-20--3.38pm
