version: 1.1.11-adhoc.40
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.40
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.40
deployedAt: 2018-12-06 10:48 pm UTC  (2018-12-06 2:48 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-12-06--2.46pm
    commitMessage: __adhoc--beta--local-enlistment--2018-12-06--2.46pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/314f849dbe4b0bd2756fca5db5c649a579bbbbd4
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-12-06--2.46pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7ddc06129cde16711d78467d7d9cadd8b2e07231
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-12-06--2.46pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/41510632f8a9fdbba3288c20c2ee4e1263c41d22
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d80a52560cdd9d8cf4bf3feb3b09f9e31b289d48
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ebf0b02ffa1c9c3be8ea39c49e6b12e61c1f7575
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-12-06--2.46pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.40/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.40/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/464698408