tag: adhoc
history:
    adhocBranchName: __adhoc--release--local-enlistment--2018-08-30--3.37pm--wandyezj-first
    commitMessage: __adhoc--release--local-enlistment--2018-08-30--3.37pm--wandyezj-first
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ad0806b0dbe27b82264acfd5d6e26490cf11c7b1
            message: >-
                JS dist files --
                __adhoc--release--local-enlistment--2018-08-30--3.37pm--wandyezj-first
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1ff0f359602842fa4a73cd87d50c7949cbf1b418
            message: >-
                Localized strings --
                __adhoc--release--local-enlistment--2018-08-30--3.37pm--wandyezj-first
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8c32eee4694121fead19a13fad19bdda95f5fbfe
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8419f6ce05e48886cb2673b897f8006aad97caf3
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9dc438c188b778882cc0417356ef422141d3b97e
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--local-enlistment--2018-08-30--3.37pm--wandyezj-first
