version: 1.1.11-adhoc.16
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.16
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.16
deployedAt: 2018-11-09 10:17 pm UTC  (2018-11-09 2:17 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-11-09--2.13pm
    commitMessage: __adhoc--beta--local-enlistment--2018-11-09--2.13pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/02b1b0a80767acfe13cdf6fb519a9e5a51cb8831
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-11-09--2.13pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0e10e61e7660802d990b9e1aa66e1dba2cd6f4d1
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-11-09--2.13pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9cea5c269b73aa9a8eff5d9d994405b238c6ebb9
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3d96ced129179f64d8bf5562104cb821fcfbe73c
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f8a205ee1cd3a770157c2f77030f0925ca94661a
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-11-09--2.13pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.16/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.16/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/453093807