tag: custom-functions-preview-refresh
history:
    adhocBranchName: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-31--9.23pm
    commitMessage: >-
        __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-31--9.23pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bed920317fd1d93ee5e8acc98a91251ca300066a
            message: >-
                JS dist files --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-31--9.23pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/99491552d4c4375625634725e6cc2d36568f9918
            message: >-
                Localized strings --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-31--9.23pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9d4c905e585b0f7b5a017ebe4924ed8bb626aba2
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5fc3c8e94a83cf0fe379865e382a122fc1888e82
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/34a517240901e7842da452f206170b411f27047d
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--custom-functions-preview-refresh--beta--local-enlistment--2018-08-31--9.23pm
