tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-13--9.27am
    commitMessage: __adhoc--beta--local-enlistment--2019-02-13--9.27am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9697a1f728facd02c5e2239afaa747f7980c1c91
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-13--9.27am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/95b44a9bb53f4bf59366bf90909cd95117cde8ee
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-13--9.27am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/13f7460b69d0c9d46f23c297e58aa14615bb1174
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7f9c921b71d01d1259e6695616949094f2e68deb
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ba5abe3af762082a57a169b6a969e3abb01deb7f
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-13--9.27am
