tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-06--3.50pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-06--3.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c6505bd91928551dfe3f0adf12c0464a89872b28
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-06--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7228fe049d3559b5e1df828193e4c5d832a21257
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-06--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/07873c8fd77e1302aaf44c141bec46fbe0fc3ec7
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1a03197a14e50bacf38561cc87d36ce396d6484f
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7c5b3dc3f77a594796bce21ce7ba7f4096ae19bc
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-06--3.50pm
