tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-10-26--5.57pm
    commitMessage: __adhoc--beta--local--2018-10-26--5.57pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/95c5c03c7c8542880b297e425818336db5eebae8
            message: JS dist files -- __adhoc--beta--local--2018-10-26--5.57pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1552c2b6f0835c7b7d722301189d51ab73daca4a
            message: Localized strings -- __adhoc--beta--local--2018-10-26--5.57pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/21ab11d1c52034f57bdb1d4c315c0443b2f29c63
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f27d42b9c34f49d25a04173b0002fd84f5ee87bf
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/daa2e23db82f11f7b8cb1a215076bb05bcabf2fc
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-10-26--5.57pm
