tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-12-06--10.35pm
    commitMessage: __adhoc--beta--local--2018-12-06--10.35pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/847f10de4f4c1ddbe7e178a898766bd93af9ba51
            message: JS dist files -- __adhoc--beta--local--2018-12-06--10.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/df4d62c6111a3162070cd20868dff371d912fac2
            message: Localized strings -- __adhoc--beta--local--2018-12-06--10.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/01d4b472ec7e30ed42cd22f6130977fe72f4811e
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dc6c369cd27b52bf6506ba59a320fe586a840832
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5d00c712d9b6e3de2c8bb0f0e5e7baad6a95831e
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-12-06--10.35pm
