tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-11-16--3.41pm
    commitMessage: __adhoc--beta--local-enlistment--2018-11-16--3.41pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/707ab454274a523e2dbb87d3ef25ab893f781a43
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-11-16--3.41pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/31c3ad0eede16396cc9e3bf056f4114c792607ea
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-11-16--3.41pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ec9fde2192db04198b985e8f1390c23ab300b88f
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b4b38a1790d8c55eea4b1d5a77d8e2272a3d21b1
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ed1d40a8952366c7a4f28d26cc7ef4a34aa3532e
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-11-16--3.41pm
