version: 1.1.11-adhoc.126
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.126
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.126
deployedAt: 2019-03-01 12:01 am UTC  (2019-02-28 4:01 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-28--3.59pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-28--3.59pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/65bd08b5cfa4b865b3e445b1fa76f85a6880be49
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-28--3.59pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/40fdbc4be7d913a5d394723a83cbec90a570e9d8
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-28--3.59pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e1b5768709666ef5da244d7c679aeb31b1893cd4
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/445685d6dbecfef9b035507ece7c8683798631a7
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/64434518df243278e367769b85ba65ddc6733d6e
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-28--3.59pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.126/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.126/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/500091179