version: 1.1.11-adhoc.133
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.133
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.133
deployedAt: 2019-03-07 3:02 am UTC  (2019-03-06 7:02 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-03-06--6.58pm
    commitMessage: __adhoc--beta--local-enlistment--2019-03-06--6.58pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/92ba8f5ad2f1d08276bd4a444552081bdd67e906
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-03-06--6.58pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/56ced557a8b66f8157aa55e21813a3b5336b7537
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-03-06--6.58pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2ed207112b9785f0550a27e1e9a84f684f405e28
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9c3fef9c65a8d680a59d0c363ba535fcb24123dc
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0cb0f0ccbf653c2d7a78f7c17cb5cd11d7b2e871
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-03-06--6.58pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.133/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.133/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/502892119