tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-11-28--4.13pm
    commitMessage: __adhoc--beta--local-enlistment--2018-11-28--4.13pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/df9f9f739b7c55c37354877c8ea993f7a0168fb8
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-11-28--4.13pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4b3545856267203494cfe873c42c63ef867f13ce
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-11-28--4.13pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/58991b7c992b675009b4761bf91acd37156796e7
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/251be27cabbfcbef8ec775d759566792c6288d82
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3f5bf805245a56af44551c91a6394b60f32992aa
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-11-28--4.13pm
