tag: adhoc
history:
    adhocBranchName: __adhoc--current--local--2018-12-10--12.05pm--MRTest
    commitMessage: Test 2 for MR
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/40b3e7a70e2c7df6ae10eb3eef58e403b141cff6
            message: JS dist files -- Test 2 for MR
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bb944135125498c3a2cd9550a734d82544c7f5bc
            message: Localized strings -- Test 2 for MR
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7044e8b8861ddeb384f658d8769be2f999f9b663
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/af1dabc10b25beed557218fc0425398ada1adc75
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e6590270d3ceb3fce25b36da5532f70c4a7b8bf4
            message: '[BEGIN PUBLISH UPDATES] -- Test 2 for MR'
