version: 1.1.11-adhoc.89
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.11-adhoc.89
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.11-adhoc.89
deployedAt: 2019-02-11 9:30 pm UTC  (2019-02-11 1:30 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2019-02-11--1.25pm
    commitMessage: __adhoc--beta--local-enlistment--2019-02-11--1.25pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e43a348acf183a9a625439b2f8771562947bf677
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2019-02-11--1.25pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/20ca8419748b2121d47ce1ba794fa460b83b810b
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2019-02-11--1.25pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4722fee4e1a1fc7de774dc150a5abd3fe17602e1
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f51292012a1733e31973f97fe4d897c58d603ff8
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6922bebd0714297c488c788c6a40b893f39625b3
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2019-02-11--1.25pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.89/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.11-adhoc.89/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/491847597