tag: adhoc
history:
    adhocBranchName: __adhoc--release--16.0.11420.35451--2019-02-21--12.08pm
    commitMessage: __adhoc--release--16.0.11420.35451--2019-02-21--12.08pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b1dea29813c14e8dd63bcc21960b6050466dce94
            message: >-
                JS dist files --
                __adhoc--release--16.0.11420.35451--2019-02-21--12.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ad3d797415957174ecd736ed6d41b623a4ab3f71
            message: >-
                Localized strings --
                __adhoc--release--16.0.11420.35451--2019-02-21--12.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4b81eb5582472bae60168331ed5b394680204d6b
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/02c963fd999fcb601a9c4093e847cdc22848ad64
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0cd6c74c6cf1e1e48085df1e2fa643024aa89b52
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--16.0.11420.35451--2019-02-21--12.08pm
